### ISSUE TITLE
Writing Project

### ISSUE THREAD

**Issue by X1las** [X1las/catformer#35]
# Others:

- [x] Abstract
- [x] Student numbers on first page **everyone**

- [x] Read through/proof reading **Especially stine**

- [x] Write Testing Outline

- [x] Write User Guide 

- [x] fix PyGame or pygame -> Pygame
- [x] introduction to all sections **Matthias** (remember to sum up previous section)
- [x] .attribute and method()
- [x] change "function" to "method" most places
# Introduction:
<details>
<summary> done tasks </summary>

- [x] Revise whole introduction section **Stine**

- [x] Write report structure paragraph

- [x] Fix requirements (such as add enemies/water) **Matthias**

</details>

# Analysis:

- [x] Fix ray intersect figure **Stine**
- [x] rewrite ray intersect paragraph to match figure **Stine**
- [x] write together/remove something in collision detection decision 

- [x] Add screen coordinate figure **Kata**

- [x] Update flip/display **Jonas**

# Implementation:

<details>
<summary> done tasks </summary>

- [x] add why sprites are not floating to all sprite sections **Kata**
- [x] remove all moving platform within other sprites **Matthias**
- [x] Write about Class Structure **Jonas**
- [x] fix class diagram **Jonas**
- [x] Rewrite first paragraph of menu **Matthias**

- [x] Write Section About the Player **Kata**
- [x] fix collision handling **Kata**
- [x] Write box section **Kata**
- [x] Vector section **Stine**

- [x] Write Section about Sprites and CustomSprite
- [x] Add sprite images **Stine**
- [x] Write Section about File Management, i.e. level/playerdata loading and saving
- [x] Write about enemies (Stine)

</details>

# Testing:
<details>
<summary> done tasks </summary>

- [x] Write testing time stamps/pass-failed **Matthias**

- [x] Fix table **Stine**

- [x] make sure it fits requirements **Matthias**
- [x] during testing we saw that player still has velocity when restarting **Matthias**
- [x] future work **Matthias** and ?

</details>

# Conclusion!

- [x] write it :)

**Comment by stine-fohrmann** [comment]
frickin finally :)
